// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fullCusip
std::string fullCusip(const std::string& s);
RcppExport SEXP _SEC13Flist_fullCusip(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(fullCusip(s));
    return rcpp_result_gen;
END_RCPP
}
// isCusip
bool isCusip(const std::string& s);
RcppExport SEXP _SEC13Flist_isCusip(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(isCusip(s));
    return rcpp_result_gen;
END_RCPP
}
// isIsin
bool isIsin(const std::string& s);
RcppExport SEXP _SEC13Flist_isIsin(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(isIsin(s));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SEC13Flist_fullCusip", (DL_FUNC) &_SEC13Flist_fullCusip, 1},
    {"_SEC13Flist_isCusip", (DL_FUNC) &_SEC13Flist_isCusip, 1},
    {"_SEC13Flist_isIsin", (DL_FUNC) &_SEC13Flist_isIsin, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SEC13Flist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
