# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Check validity of CUSIP code
#'
#' @description This function check validity of CUSIP code by comparing calculated checksum digit based on first 8 characters of CUSIP code with 9th character of CUSIP code - checksum digit
#' @param s nine-character string with CUSIP code to validate
#' @keywords CUSIP checksum digit
#' @return Logical value indicating validity of CUSIP number: \code{TRUE} if CUSIP number is valid, \code{FALSE} if CUSIP number is invalid
#' @examples
#' library(SEC13Flist)
#' isCusip("B38564109") #invalid CUSIP example
#' isCusip("B38564108") #valid CUSIP example
#' @export
isCusip <- function(s) {
    .Call(`_SEC13Flist_isCusip`, s)
}

