# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Check validity of CUSIP code
#'
#' @description This function check validity of CUSIP code by comparing calculated check digit based on first 8 characters of CUSIP code with 9th character of CUSIP code - control digit
#' @param s nine-character string with CUSIP code to validate
#' @keywords CUSIP Control Digit
#' @export
isCusip <- function(s) {
    .Call(`_SEC13Flist_isCusip`, s)
}

